### ISSUE TITLE
Color accuracy feels way off.

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#44]
![image](https://github.com/user-attachments/assets/4f0267e9-9040-4f5a-a786-005932c0d855)
![454342965_512630764630281_2632036676241669727_n](https://github.com/user-attachments/assets/3f3657de-121d-4db3-bb26-9442af9b6ed4)

Please test this on your device to see the discrepancy.
Json:
{"flags":14,"num_leds":28,"single_pats":[{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0},{"args":[6,9,39,0,0],"colorset":["0x0fff00","0x0015ff","0xaa0012"],"flags":0,"numColors":3,"pattern_id":0}]}

**Comment by Unreal-Dan** [comment]
This is just how leds display colors, there's nothing I can do. 

Alas, I will try to humour you.

Set the red to 1 and blue to 1 intensity each.

Turn off one channel at a time and observe the 'intensity' of a 1 blue or 1 red and how the two impact the color when they're added together.

The goal is to get the idea of how powerful a '1 blue' is on it's own, it's actually quite bright, and quite blue.  

Once you have a good idea of what they look like at 1 intensity each, turn up one channel like the red to say 180 red and flick the blue on and off again at 1 intensity. 

Do you agree or disagree that adding the 1 intensity blue to the 180 red should make that pink or not?  ie. is the LED misbehaving somehow? Or is a 180 red on the LED + a 1 blue on the led... truly just pink?

I believe it is truly just pink when you have a 180 "led" red + 1 "led" blue.  There is no bug in rendering.

Here is some adafruit engineers on the same topic saying the exact same thing:
https://forums.adafruit.com/viewtopic.php?t=51369

Now, all of this said, we just circle back to the original answer to this:  We should not lie to people about what color they are using, that will be more problematic and cause more confusion than if they just have to learn that leds look different because computer monitors aren't using additive lighting the way rgb leds are.

Closing because I personally believe lying about the color you're using and rendering it 'different' on the screen to makeup for the difference is a giant mistake and I'm not interested in spending time to fix it.  I truly believe people will get more confused if we apply some kind of masking layer to make the colors look different.
