### ISSUE TITLE
Single clicking the up or down arrows in the RGB sliders continuously raises the value.

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#50]
You would expect it raises or lower the value by 1 but once you've clicked the arrow it will continuously raise or lower the value as long as your cursor is over one of the arrow buttons.

**Comment by Unreal-Dan** [comment]
Yeah I expected the same thing and couldn't solve this for the life of me, I think it might actually just be native to how that specific numeric input box works -- that or a feedback loop from refreshing/redrawing the UI since each input element effects the other elements it's possible to cause a sort of feedback loop where changing one causes the other to change.

However, I don't think it's a feedback loop, I think the god damn control just works that way. Will need to create custom input boxes to fix it I think, or switch to regular text boxes rather than numeric input boxes

**Comment by Unreal-Dan** [comment]
I changed them to just be text boxes lol not numeric
